### PR TITLE
Allow to enable/disable plugin with more granularity with pytest markers

### PR DESCRIPTION
**Pull request by cdessez**
It can be useful to enable/disable this pytest plugin on a per-test or
per-module granularity.

This commit allows to achieve that by using pytest markers.
See README.rst and tests for concrete examples.

### CODE REVIEW

**Comment by cdessez** [comment]
@nirs would you mind taking a look at this PR?
Thanks,
Cedric

**Comment by nirs** [comment]
@cdessez Thanks for this awesome contribution! I will review and test this later.

 Looks like both Travis and appveyor CI are broken. We really need to setup github actions for this project.

Can you add more info on how this was tested (plaftorms, python versions)?

**Comment by cdessez** [comment]
Thanks for the prompt reply @nirs!

For now I've been able to run the unit tests (`test_threadleak.py`) locally on MacOS for python version 2.7, 3.7, 3.9 and 3.10.
Flake8 also runs without issue on 3.10.
Here is the corresponding tox summary:
```
___________________________________ summary ___________________________________
  py27: commands succeeded
SKIPPED:  py33: InterpreterNotFound: python3.3
SKIPPED:  py34: InterpreterNotFound: python3.4
SKIPPED:  py35: InterpreterNotFound: python3.5
SKIPPED:  py36: InterpreterNotFound: python3.6
  py37: commands succeeded
SKIPPED:  py38: InterpreterNotFound: python3.8
  py39: commands succeeded
  py310: commands succeeded
SKIPPED:  pypy: InterpreterNotFound: pypy
  flake8: commands succeeded
  congratulations :)
```

Besides, I've also been able to verify the behaviour locally by using the new pytest marker in a project of mine to disable the plugin on specific tests. That was in a virtual environment running python3.8.

**Comment by cdessez** [comment]
@nirs I've just added a commit that migrates the tests CI from Travis and appveyor to Github actions. That seems to work well on my fork.

Note that I've only included python 3 version from 3.6 up. I kind of doubt it's any useful to include any older version. If the tests pass on 2.7 and 3.6, I guess it's reasonable to think it'll work for 3.3, 3.4 and 3.5 too.

Not sure what the process is to create/push a new release to PyPI, but it does not seem to be part of the CI so far so I assume it's a manual process on your side.

Let me know if I can help further with anything that's in the way of merging this PR 😃. Thanks!

**Comment by cdessez** [comment]
For reference, here is a link to the Actions workflow triggered by the latest commit I pushed: https://github.com/cdessez/pytest-threadleak/actions/runs/1684008561

**Comment by cdessez** [comment]
@nirs any reason not to merge and release at this point?

If there are any further checks that you'd like to perform, I can maybe do it or automated them into the CI.

**Comment by nirs** [comment]
Thanks @cdessez, I will release new version next week.

**Comment by nirs** [comment]
@cdessez 0.4.0 released, thanks again for your contribution!

**Pull request merged**
